return {
  -- 成就系统
  ["workshop-1840284484"]={
    ["configuration_options"]={
      [""]=0,
      ["ABSORBGAIN"]=0.01,
      ["BUILDXP"]=true,
      ["CAVES"]=true,
      ["COSTRAISE"]=true,
      ["DAMAGEGAIN"]=0.01,
      ["EXPMULT"]=1,
      ["FOODXP"]=true,
      ["GEAR"]="nothing",
      ["HEALTHGAIN"]=3,
      ["HEALTHPENALTY"]=true,
      ["HIDEPERK"]="none",
      ["HUNGERGAIN"]=3,
      ["INSULATIONGAIN"]=10,
      ["KILLXP"]=true,
      ["LANGUAGE"]="chs",
      ["LEVELPOINTS"]=3,
      ["LEVELXP"]=2000,
      ["MANDRAKEBOI"]=true,
      ["MULT"]=1,
      ["NOAWARDS"]=false,
      ["NOTIFICATION"]=true,
      ["PLAYS"]=1,
      ["REFUND"]=0.85,
      ["SANITYGAIN"]=3,
      ["SPEEDGAIN"]=0.01,
      ["SYSTEM"]="both",
      ["UNLOCKXP"]=true,
      ["WORKXP"]=true,
      ["absorbup"]=true,
      ["ancientstation"]=true,
      ["animallover"]=true,
      ["archmage"]=true,
      ["buildmaster"]=true,
      ["cheatdeath"]=true,
      ["chopmaster"]=true,
      ["cookmaster"]=true,
      ["crit"]=true,
      ["damageup"]=true,
      ["doubledrop"]=true,
      ["engineering"]=true,
      ["fastworker"]=true,
      ["firebody"]=true,
      ["fireflylightup"]=true,
      ["fishmaster"]=true,
      ["goodman"]=true,
      ["healthregen"]=true,
      ["healthup"]=true,
      ["hungerrateup"]=true,
      ["hungerup"]=true,
      ["icebody"]=true,
      ["krampusxmas"]=true,
      ["lifesteal"]=true,
      ["lunarcraft"]=true,
      ["masterchef"]=true,
      ["minemaster"]=true,
      ["nanobots"]=true,
      ["naturalist"]=true,
      ["nomoist"]=true,
      ["pickmaster"]=true,
      ["reader"]=true,
      ["refresh"]=true,
      ["sanityregen"]=true,
      ["sanityup"]=true,
      ["scale"]=true,
      ["shrine"]=true,
      ["speedup"]=true,
      ["supply"]=true 
    },
    ["enabled"]=true 
  },
  -- ANCHOR epic 史诗级血量
  ["workshop-1185229307"]={
    ["configuration_options"]={
      [""]="",
      ["damage"]=true,
      ["noepic"]=false,
      ["nonoepic"]=false,
      ["offset"]=0,
      ["phase"]=true 
    },
    ["enabled"]=true 
  },
-- ANCHOR 智能小木牌
["workshop-1595631294"]={
  configuration_options={
    BundleItems=false,
    ChangeSkin=true,
    Digornot=false,
    DragonflyChest=false,
    Icebox=false,
    SaltBox=false 
  },
  enabled=true 
},
-- ANCHOR 神话书说角色
["workshop-1699194522"]={ configuration_options={ Skillbadge=true }, enabled=true },
-- ANCHOR 神话书说主题
["workshop-1991746508"]={ configuration_options={ Language="CHINESE", ShowBuff=true }, enabled=true },
-- ANCHOR 木牌传送 (GUI)
["workshop-2119742489"]={
  configuration_options={ Hunger_Cost=1, Ownership=false, Sanity_Cost=1 },
  enabled=true 
},
-- ANCHOR 额外的装备格子
["workshop-2324689937"]={
  configuration_options={
    ["config_render"]=true,
    ["slot_amulet"]="extrabody3",
    ["slot_armor"]="extrabody1",
    ["slot_backpack"]=false,
    ["slot_band"]=false,
    ["slot_clothing"]="extrabody2",
    ["slot_heavy"]=false,
    ["slot_lifevest"]=false,
    ["slot_shell"]=false 
  },
  enabled=true 
},
-- ANCHOR Boss预测器
["workshop-2510473186"]={
  configuration_options={
    antlion=true,
    atrium_gate_cooldown=true,
    atrium_gate_destable=true,
    bearger=true,
    beequeenhive=true,
    crabking_spawner=true,
    deerclops=true,
    dragonfly_spawner=true,
    fruitfly=false,
    klaus=true,
    malbatross=true,
    null=0,
    prioritytype="leasttimefirst",
    showname=false,
    toadstool=true 
  },
  enabled=true 
},
-- ANCHOR 猎犬预测器
["workshop-2512988342"]={ configuration_options={  }, enabled=true },
-- ANCHOR 全球定位
["workshop-2528036914"]={
  configuration_options={
    ENABLEPINGS=true,
    FIREOPTIONS=2,
    OVERRIDEMODE=false,
    SHAREMINIMAPPROGRESS=true,
    SHOWFIREICONS=true,
    SHOWPLAYERICONS=true,
    SHOWPLAYERSOPTIONS=2 
  },
  enabled=true 
},
-- ANCHOR 每个背包格子数量
["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=250 }, enabled=true },
-- ANCHOR 血量显示
["workshop-375859599"]={
  configuration_options={
    divider=5,
    random_health_value=0,
    random_range=0,
    send_unknwon_prefabs=false,
    show_type=0,
    unknwon_prefabs=1,
    use_blacklist=true 
  },
  enabled=true 
},
-- ANCHOR 复活
["workshop-462434129"]={
  configuration_options={
    MOD_RESTART_ALLOW_KILL=true,
    MOD_RESTART_ALLOW_RESTART=true,
    MOD_RESTART_ALLOW_RESURRECT=true,
    MOD_RESTART_CD_BONUS=0,
    MOD_RESTART_CD_KILL=3,
    MOD_RESTART_CD_MAX=0,
    MOD_RESTART_CD_RESTART=5,
    MOD_RESTART_CD_RESURRECT=0,
    MOD_RESTART_FORCE_DROP_MODE=0,
    MOD_RESTART_IGNORING_ADMIN=true,
    MOD_RESTART_MAP_SAVE=1,
    MOD_RESTART_RESURRECT_HEALTH=0,
    MOD_RESTART_TRIGGER_MODE=1,
    MOD_RESTART_WELCOME_TIPS=true,
    MOD_RESTART_WELCOME_TIPS_TIME=6 
  },
  enabled=true 
},
-- ANCHOR 快速采集
["workshop-501385076"]={
  configuration_options={
    quick_cook_on_fire=true,
    quick_harvest=true,
    quick_pick_cactus=true,
    quick_pick_plant_normal_ground=true 
  },
  enabled=true 
},
-- ANCHOR 持久挖矿
["workshop-604761020"]={
  configuration_options={
    RUOYINXIAN=false,
    SHENGDANSHI=false,
    baoshibaolv=1,
    blue_baoshi=1,
    er_shuoming=0,
    green_baoshi=1,
    huangjinbaolv=1,
    marble_suipian=1,
    orange_baoshi=1,
    purple_baoshi=1,
    red_baoshi=1,
    shishengzhang=0,
    shitoubaolv=1,
    thulecite_xiukuang=1,
    wajuecishu=2,
    yellow_baoshi=1,
    yi_shuoming=0 
  },
  enabled=true 
},
-- ANCHOR Show me 鼠标悬停信息展示
["workshop-666155465"]={
  configuration_options={
    chestB=-1,
    chestG=-1,
    chestR=-1,
    display_hp=-1,
    food_estimation=-1,
    food_order=0,
    food_style=0,
    lang="chs",
    show_food_units=-1,
    show_uses=-1 
  },
  enabled=true 
},
-- ANCHOR 防卡  
["workshop-2505341606"]={
  configuration_options={
    ANNOUNCE_MODE=true,
    CLEANDAYS=15,
    axe=3,
    bee=10,
    beefalo=50,
    birdtrap=10,
    blueprint=3,
    bugnet=3,
    burntground=5,
    clean=true,
    compass=3,
    cutgrass=50,
    deer=10,
    driftwood_log=130,
    earmuffshat=3,
    evergreen_sparse=150,
    feather=2,
    festival=2,
    firehound=10,
    fishingrod=3,
    flies=10,
    flint=50,
    frog=20,
    glommerfuel=10,
    guano=1,
    hammer=3,
    heatrock=10,
    hound=10,
    houndstooth=10,
    lang=true,
    log=50,
    manrabbit_tail=20,
    marsh_tree=100,
    mosquitosack=10,
    nitre=50,
    oceanfishingrod=3,
    pickaxe=3,
    pinecone=50,
    pitchfork=3,
    pocket_scale=3,
    poop=5,
    razor=3,
    rock_petrified_tree=150,
    rocks=50,
    rocky=20,
    rottenegg=2,
    seeds=3,
    shovel=3,
    silk=10,
    skeleton_player=20,
    slurtle=5,
    slurtleslime=2,
    spear=3,
    spider=10,
    spiderden=40,
    spidergland=10,
    spoiled_fish=2,
    spoiled_food=2,
    stack=true,
    stinger=2,
    torch=3,
    trap=40,
    twiggytree=150,
    twigs=50,
    winterhat=3 
  },
  enabled=true 
},
-- ANCHOR 移动建筑
["workshop-1079538195"]={
  configuration_options={
    beebox=true,
    birdcage=true,
    cartographydesk=true,
    cookpot=true,
    dragonflychest=true,
    dragonflyfurnace=true,
    endtable=true,
    firesuppressor=true,
    icebox=true,
    lightning_rod=true,
    meatrack=true,
    modsupport=true,
    moondial=true,
    mushroom_farm=true,
    mushroom_light=true,
    nightlight=true,
    perdshrine=true,
    pottedfern=true,
    rainometer=true,
    researchlab=true,
    researchlab2=true,
    researchlab3=true,
    researchlab4=true,
    resurrectionstatue=true,
    saltlick=true,
    scarecrow=true,
    sculptingtable=true,
    succulent_potted=true,
    townportal=true,
    treasurechest=true,
    wardrobe=true,
    winterometer=true 
  },
  enabled=true 
},
-- ANCHOR 狗头
["workshop-2002991372"]={
  configuration_options={
    ["Q for lol"]=99,
    Q_coolingtime=5,
    ["R for lol"]=118,
    R_consume=300,
    R_duration=40,
    check_souls=122 
  },
  enabled=true 
}
}